sudo: false
language: node_js

node_js:
  - 8
  - 10
  - 12

before_install:
 - npm install --global npm@
before_install: >
  node_version=$(node -v);
  if  [ ${node_version:1:1} = 6 ]; then
      npm install --global npm@^4
    else
      npm install --global npm@latest
  fi

script:
 - npm run build_and_test
 - npm run lint
