title: typedoc-site
description: > # this means to ignore newlines until "baseurl:"
  TypeDoc official site.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "typedoc.org" # the base hostname & protocol for your site

collections:
  guides:
    permalink: /guides/:title/
    output: true

# Build settings
markdown: kramdown

plugins:
  - jekyll-redirect-from

sass:
  style: compressed

include:
  - "*.html" # Needed to include files that start with underscore

exclude:
  - images/edit
  - Gemfile
  - Gemfile.lock
  - README.md
